// Author: ramanpal singh | URL: https://kwebby.com
import type { FieldSpec } from "./types";
export const moduleFields: Record<string, FieldSpec[]> = {
    leads: [
        { name: "name", label: "Full name", required: true },
        {
            name: "email",
            label: "Email address",
            type: "email",
            required: true,
        },
        { name: "phone", label: "Phone" },
        {
            name: "issue_category",
            label: "Practice area",
            type: "select",
            options: [
                "civil",
                "commercial",
                "employment",
                "family",
                "criminal",
                "property",
                "other",
            ],
        },
        { name: "jurisdiction", label: "Jurisdiction" },
        {
            name: "source",
            label: "Lead source",
            type: "select",
            options: [
                "website",
                "referral",
                "notice_explainer",
                "consultation_tool",
                "email",
                "phone",
                "other",
            ],
        },
        {
            name: "status",
            label: "Stage",
            type: "select",
            options: [
                "new",
                "contacted",
                "intake",
                "conflict_review",
                "consultation",
                "lost",
                "closed",
            ],
        },
        {
            name: "urgency",
            label: "Urgency",
            type: "select",
            options: ["normal", "urgent"],
        },
        { name: "next_action", label: "Next action" },
        { name: "next_action_at", label: "Follow-up date", type: "date" },
        { name: "notes", label: "Intake notes", type: "textarea" },
    ],
    contacts: [
        { name: "name", label: "Name", required: true },
        {
            name: "kind",
            label: "Type",
            type: "select",
            options: ["person", "organization"],
        },
        { name: "email", label: "Email", type: "email" },
        { name: "phone", label: "Phone" },
        { name: "address", label: "Address", type: "textarea" },
        {
            name: "safe_contact",
            label: "Safe contact preferences",
            type: "textarea",
        },
        { name: "notes", label: "Notes", type: "textarea" },
    ],
    matters: [
        { name: "title", label: "Matter title", required: true },
        { name: "practice", label: "Practice area" },
        { name: "jurisdiction", label: "Jurisdiction" },
        {
            name: "status",
            label: "Status",
            type: "select",
            options: ["active", "on_hold", "closed"],
        },
        {
            name: "confidentiality",
            label: "Confidentiality",
            type: "select",
            options: ["standard", "restricted"],
        },
        {
            name: "scope",
            label: "Agreed scope",
            type: "textarea",
            required: true,
        },
        {
            name: "closure_notes",
            label: "Closure notes",
            type: "textarea",
            hint: "Required when closing a matter.",
        },
    ],
    tasks: [
        { name: "title", label: "Task", required: true },
        {
            name: "matter_id",
            label: "Matter ID",
            hint: "Paste the ID of the related matter.",
        },
        { name: "due_at", label: "Due date", type: "date" },
        {
            name: "status",
            label: "Status",
            type: "select",
            options: ["open", "in_progress", "review", "done", "cancelled"],
        },
        {
            name: "priority",
            label: "Priority",
            type: "select",
            options: ["normal", "urgent"],
        },
        {
            name: "date_source",
            label: "Source of date",
            hint: "Order, rule or verified instruction supporting the date.",
        },
        { name: "notes", label: "Instructions", type: "textarea" },
    ],
    proceedings: [
        { name: "title", label: "Proceeding title", required: true },
        { name: "matter_id", label: "Matter ID", required: true },
        { name: "court", label: "Court or agency" },
        { name: "case_reference", label: "Case reference" },
        { name: "hearing_at", label: "Hearing date", type: "date" },
        {
            name: "date_source",
            label: "Source of hearing date",
            hint: "Required for scheduled hearings.",
        },
        {
            name: "status",
            label: "Status",
            type: "select",
            options: ["active", "filed", "served", "adjourned", "closed"],
        },
        { name: "notes", label: "Notes", type: "textarea" },
    ],
    team: [
        { name: "name", label: "Name", required: true },
        { name: "email", label: "Email", type: "email", required: true },
        { name: "job_title", label: "Job title" },
        { name: "skills", label: "Skills" },
        {
            name: "status",
            label: "Status",
            type: "select",
            options: ["active", "on_leave", "inactive"],
        },
    ],
};
